### ISSUE TITLE
Restarted sims deviate from uninterrupted.

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#251] opened 2019-03-20 17:56 UTC
I haven't used the restart feature much yet, but on a 512**3 hydro sim I ran a quick test earlier, restarting at z=2.25 and evolving to z=2 and below are the power spectra in the sim that had no restart vs the restarted one. The power on large scales agrees well, but in the non-linear regime there appears to be a non-negligible difference between the final outputs. 

![mpgadget_restart](https://user-images.githubusercontent.com/16047009/54707027-20ad7080-4b38-11e9-96f6-b33e5474db69.png)

I guess this is could be some numerical rounding error that happens after the particle data is saved and reloaded, but not sure why this would result in consistently more non-linear power in the restarted sim, and to such a large degree.

**Comment by sbird** [comment] 2019-03-20 18:01
uh, that's a lot. It should not do that (and we actually put some effort into ensuring that it doesn't!) Can you post your config here?

**Comment by sbird** [comment] 2019-03-20 18:02
A restart will not be quite bit identical, but should be close.

**Comment by Chris-Pedersen** [comment] 2019-03-20 18:06
Sure, included the restarted.out file too in case there's any hint in there:

[paramGenic.txt](https://github.com/MP-Gadget/MP-Gadget/files/2989515/paramGenic.txt)
[paramGadget.txt](https://github.com/MP-Gadget/MP-Gadget/files/2989516/paramGadget.txt)
[13546out.txt](https://github.com/MP-Gadget/MP-Gadget/files/2989517/13546out.txt)

**Comment by sbird** [comment] 2019-03-20 18:10
Build config and matter power/transfer too please (unless you are using one of the standard ones).

**Comment by Chris-Pedersen** [comment] 2019-03-20 18:13
Ah in fact I just realised I ran this test on an old version of the code from August 2018 (we've been trying to stick to the same version for the sake of consistency). Let me rerun on the latest master and I'll see if the problem goes away.

**Comment by sbird** [comment] 2019-03-20 18:22
Ah! Yes, that is quite possible. I think I did fix a few bugs like this in the interim.

**Comment by sbird** [comment] 2019-03-20 18:25
From memory there was something with the initialisation of the softening lengths that could have done this.

**Comment by Chris-Pedersen** [comment] 2019-03-21 20:25
I tried again using a 256**3 sim on latest master and get the same:

![restart256](https://user-images.githubusercontent.com/16047009/54782612-3776c480-4c17-11e9-8dd6-15722d7db281.png)

I've attached all files below (although we're just using a standard config and linear power from make_class_power). They have to end in .txt or github gets upset.

[paramfileGenic.txt](https://github.com/MP-Gadget/MP-Gadget/files/2993831/paramfileGenic.txt)
[paramfileGadget.txt](https://github.com/MP-Gadget/MP-Gadget/files/2993833/paramfileGadget.txt)
[matterpowdat.txt](https://github.com/MP-Gadget/MP-Gadget/files/2993834/matterpowdat.txt)
[transferdat.txt](https://github.com/MP-Gadget/MP-Gadget/files/2993835/transferdat.txt)
[Optionsmk.txt](https://github.com/MP-Gadget/MP-Gadget/files/2993837/Optionsmk.txt)

**Comment by sbird** [comment] 2019-03-22 23:33
Thanks, I'm on this.

**Comment by sbird** [comment] 2019-03-23 02:44
hmm, do you have the output log from the restart and the non-restart runs? There are two possibilities that I see and would like to investigate.

**Comment by sbird** [comment] 2019-03-23 03:39
Can reproduce on single-node openmp.

**Comment by rainwoodman** [comment] 2019-03-23 04:34
I useful check is restart and immediately dump, then see what has changed.

**Comment by sbird** [comment] 2019-03-23 05:44
Can *not* reproduce with hydro and sfr turned off. Gravity is fine.

**Comment by sbird** [comment] 2019-03-23 07:44
Star formation is ten times larger in the first timestep after the restart, which smells fishy.

**Comment by sbird** [comment] 2019-03-23 20:10
Ah, I see it. In sfr_eff.c we have:
    double dloga = get_dloga_for_bin(P[i].TimeBin);
    double unew = DMAX(All.MinEgySpec,
            (SPHP(i).Entropy + SPHP(i).DtEntropy * dloga) /
            GAMMA_MINUS1 * pow(SPHP(i).EOMDensity * All.cf.a3inv, GAMMA_MINUS1));

but on the first timestep TimeBin is zero! So we form too many stars in gas which is being heated.

**Comment by sbird** [comment] 2019-03-23 20:11
There will be a similar issue with black holes

**Comment by sbird** [comment] 2019-03-23 20:16
There also may be an issue with the viscosity limiting in hydra.c:

**Comment by sbird** [comment] 2019-03-23 20:27
This issue is I think only really important for quick Lyman alpha star formation, because viscosity limiting and black hole accretion happen fairly rarely. The star formation rate for the standard SH03 module is also lower so it makes a smaller difference.

However, this is a real and important bug in all cases and should be fixed. The issue comes because we don't know how long the timestep is going to be, so we don't know how many stars to form. 

Potential solutions:
1) store the particle timesteps in the snapshot, which I don't really want to do because it will break backwards compatibility and will in any case still be present in the ICs (this matters less because the ICs don't have a lot of star formation).

2) On the first timestep populate the particle timebins sooner, before SFR is run. This is preferred but will need a bit of shenaniganising.

**Comment by sbird** [comment] 2019-03-23 23:47
Ok, it seems fixing this is not sufficient. So it is something else as well. I suspect that the predicted velocity and predicted entropies are computed at the wrong time.

**Comment by sbird** [comment] 2019-03-23 23:58
So we are computing dv = Vel - VelPred in a few places to get the derivative of the velocity. VelPred is correctly set to the current velocity. But Vel is also the current velocity, so computing the derivative doesn't really make sense.

**Comment by sbird** [comment] 2019-03-24 00:49
No, hang on. I am completely wrong about this. The SFR in the SH03 model is zero on the first timestep (as it ought to be, because star formation was already applied). Ditto for the black hole. For the QLya model the star formation should be zero, in fact, because all the overdense particles should already be stars.

**Comment by sbird** [comment] 2019-03-24 01:04
haha, it is much simpler than that. The Entropy variable is not being set on reload without DENSITY_INDEPENDENT_SPH, so is being presumed to be zero! No wonder there are too many stars!

**Comment by rainwoodman** [comment] 2019-03-24 18:15
Is our time sequence `K D D F T S A K`?
K = kick 1/2 step
D = drift 1/2 step
F = force
T = time step sizes
S = sub grid physics
A = change active list

**Comment by sbird** [comment] 2019-03-25 01:03
No, it is K D D F S T K A

But I thought about it carefully and I think it is all fine.

**Closed** 2019-03-25 19:35 UTC
