### ISSUE TITLE
Linear growth of individual species

### ISSUE THREAD

**Issue by Chris-Pedersen** [MP-Gadget/MP-Gadget#211] opened 2018-04-10 17:12 UTC
This is in the same vein of what we've been emailing about but an issue might make it easier to discuss. We're looking at confirming the linear growth by running some sims with very low A_s, and comparing the results to CAMB. If we ignore the neutrino case for now, and just consider the growth of individual species with DifferentTransfersOn = 1, when comparing the power with the CAMB prediction for that species, we get (with ICs at z=99):

![z99_diffon_nu0](https://user-images.githubusercontent.com/16047009/38572106-15fa0818-3cea-11e8-9811-72bf96df4f5e.png)
![z3_diffon_nu0](https://user-images.githubusercontent.com/16047009/38572110-18fe8692-3cea-11e8-88dd-952cef5dc8a8.png)

It looks as though the species themselves aren't quite evolving in agreement with linear theory, but doing so in such a way that the total matter looks ok. This is with StarFormation on, currently rerunning with it off and I'll update if this makes a signifcant difference. Paramfiles are:

[params_ini.txt](https://github.com/rainwoodman/MP-Gadget/files/1895691/params_ini.txt)
[paramfile_genic.txt](https://github.com/rainwoodman/MP-Gadget/files/1895692/paramfile_genic.txt)
[paramfile_gadget.txt](https://github.com/rainwoodman/MP-Gadget/files/1895693/paramfile_gadget.txt)

**Comment by Chris-Pedersen** [comment] 2018-04-11 13:53
I've rerun the above with StarFormation off and Hydro off, and the issue is still present:

![z99_diffon_nu0_nosfr](https://user-images.githubusercontent.com/16047009/38620995-cb7991e2-3d97-11e8-91a1-b18a39a75e6c.png)
![z3_diffon_nu0_nosfr](https://user-images.githubusercontent.com/16047009/38621090-068eaaf6-3d98-11e8-93e1-272b6933d3b5.png)

**Comment by andreufont** [comment] 2018-04-11 17:25
Hi Yu,

It works fine when using a single transfer function.

Cheers,
Andreu

**Comment by sbird** [comment] 2018-04-11 20:37
Right, so this is related to pull #202 and issue #179 in some part. But we should leave this open because there may be another bug floating around as well.

**Comment by sbird** [comment] 2018-04-11 20:40
@Chris-Pedersen : what happens if you use the sbird:scaledepgrowth branch?

**Comment by rainwoodman** [comment] 2018-04-11 21:04
@sbird It just seems to me the initial velocity of baryons is bad.

Would it be worth-while as a test to just use the cdm initial velocity to seed the baryons? Maybe it will just fix all of the problems. 

What is the ratio between the linear velocities used in the IC of baryon and cdm? I worry the velocity terms you are using (gsl interpolated) are bad.

Here is how I obtain the velocity (dd/da):

https://github.com/rainwoodman/fastpm-python/blob/master/fastpm/multi.py#L185

Perhaps do a head to head comparison of this?

**Comment by sbird** [comment] 2018-04-11 21:07
I think you are probably right. Thanks for the fastpm link - I'll compare to that.

**Comment by Chris-Pedersen** [comment] 2018-04-13 12:11
@sbird I get the error:

[ 000004.82 ] Task 67: Could not read both transfer tables at: '' or '/share/hypatia/lya_sims/growth/camb_files/single_1p_transfer_99.dat'

When running scaledepgrowth - the transfer function definitely exists and is at the right location, do I need to modify the paramfiles in some way on this branch?

**Comment by sbird** [comment] 2018-04-13 15:35
You do. You need an extra transfer function at a later time to compute time derivatives. You can set: 
FileWithFutureTransferFunction = camb_transfer_98.99.dat
InputFutureRedshift = 98.99

**Comment by sbird** [comment] 2018-04-14 23:15
@Chris-Pedersen This is actually a really good test case, and I think should be one of the examples in the repo. Would you mind if we added it? If you sent a PR I could merge it and you would keep the authorship credit.

**Comment by Chris-Pedersen** [comment] 2018-04-16 16:34
Sure of course, I have added a PR including the CAMB data (and checked that it runs), hope everything is in order. Would you still like me to run the same tests on sbird:scaledepgrowth?

**Comment by sbird** [comment] 2018-04-16 17:54
Thanks. If you wouldn't mind checking your tests on sbird:scaledepgrowth as well, that'd help. Just to have a baseline for comparison.

**Comment by sbird** [comment] 2018-04-19 05:36
Hold the test - I think I know what is wrong and am about to change things.

**Comment by Chris-Pedersen** [comment] 2018-04-19 08:06
Ok no probs - I've got the scaledeptgrowth branch running now so let me know when you have a commit I can test.

**Comment by sbird** [comment] 2018-05-22 05:15
Linking current state here, as off #202 merging: 
tree off:
https://github.com/MP-Gadget/MP-Gadget/pull/202#issuecomment-390553785
tree on:
https://github.com/MP-Gadget/MP-Gadget/pull/202#issuecomment-390553986
looks like enabling the tree causes some inaccuracy, a loss of power of a few percent, unrelated to the ICs.

**Comment by sbird** [comment] 2018-05-22 05:16
I have also tried increasing RCUT from 4.5 to 6; it becomes a little better, but not much.

I wonder what happens if we over-sample the baryons?

**Comment by sbird** [comment] 2018-07-24 17:51
I have also tried ForceEqualTimesteps - no change.

**Comment by rainwoodman** [comment] 2018-07-24 18:30
What happens if we disable the tree?

**Comment by rainwoodman** [comment] 2018-07-24 18:30
and hydro, etc.

**Comment by sbird** [comment] 2018-07-24 18:38
If we disable the tree we reproduce the correct linear growth - hydro doesn't seem to make a lot of difference on these scales (I think it might already be off in my tests)

**Comment by sbird** [comment] 2018-07-24 18:40
I wonder if this might be related to the infamous 1% offset with neutrinos in our recent paper. In which case it might be that disabling the tree just reduces shot noise in the gravitational potential. I could try messing with the softening and see if that helps.

**Comment by rainwoodman** [comment] 2018-07-24 18:50
Did you use the hydro smoothing length for the grav smoothing of baryons?

The hydro smoothing length is shorter than the grav smoothing length near halos and larger in voids.

This could explain why growth of baryon and dm diverges.

**Comment by sbird** [comment] 2018-07-24 18:53
Wait, I already tried the softening. I remember. This run is using the standard 1/30. softening length. If we use the hydro smoothing length for the baryon grav. softening we recover the correct linear answer (because it effectively disables the tree for the baryons). Increasing the softening moderately doesn't have a big effect.

**Comment by rainwoodman** [comment] 2018-07-24 22:18
'effectively disabling the tree' because vast of bayons have very large smoothing length?

I think it is puzzling why only the linear growth of baryon is sensitive to the tree. DM shows the correct linear regardless of the tree. 

Did you have a run where baryon particles exist, hydro is disabled, and thus dm and baryon use the same gravity smoothing in tree? So bascially two CDM species of different particle masses with slightly different velocity transfer function.

Could it be the shot-noise of DM somehow affected the baryons more strongly due to the large mass difference?

**Comment by sbird** [comment] 2018-07-24 23:49
> 'effectively disabling the tree' because vast of bayons have very large smoothing length?

Yes, exactly.

> I think it is puzzling why only the linear growth of baryon is sensitive to the tree. DM shows the correct linear regardless of the tree.

Indeed - interestingly the total power spectrum is still correct: the DM is high and the baryons are low. So the overall growth is still right (probably because the gravity is conserving momentum/energy correctly?)

> Did you have a run where baryon particles exist, hydro is disabled, and thus dm and baryon use the same gravity smoothing in tree? So bascially two CDM species of different particle masses with slightly different velocity transfer function.

That's exactly what the shown run is.

> Could it be the shot-noise of DM somehow affected the baryons more strongly due to the large mass difference?

I can see that being true - I guess the test for that is to oversample the CDM so they have the same mass... Another possibility that occurred to me is that there will be a large-scale relative velocity between the baryons and CDM, but I don't know how to check for that.

**Comment by rainwoodman** [comment] 2018-07-25 00:45
"""Another possibility that occurred to me is that there will be a large-scale relative velocity between the baryons and CDM, but I don't know how to check for that.
"""

**Comment by sbird** [comment] 2018-07-25 00:48
Unless something weird is happening with the boundary conditions, or with the N-body gauge

**Comment by rainwoodman** [comment] 2018-07-25 00:56
Running the 2 fluid boltzmann solver with difftransfer and cdmtransfer from z=99 to z=3? I recall doing something similar and didn't notice big differences against the relativistic boltzmann solver. I can redo this carefully and paste the result.

Oversampling the CDM could be the way to go, or downsample the baryons by ID, replacing with the mean of 8.

**Comment by sbird** [comment] 2018-07-25 01:10
One other thing I have always wondered about: the baryons and CDM we use are slightly out of phase.

We start off with staggered grids for the CDM and baryons and then we apply zeldovich displacements evaluated at the staggered positions.

Another thing that could be done is to start off with CDM and baryons on the same grid, apply zeldovich displacements and then apply a constant shift to the baryons.

I wonder which is the right thing?

**Comment by rainwoodman** [comment] 2018-07-25 01:21
I felt the first approach is 'correct'-er than the second.
It is just asserting there are two sets of initial positions q_cdm and q_baryon.
The second will have an out of phase problem in the baryons.

The out-of-phase effect should be in the small scale only, and should have showed up in DiffTransfer = 0 runs too. We do not observe a problem there, I recall?

**Comment by rainwoodman** [comment] 2018-07-25 02:00
I assume the large scale amplitude difference will quickly become large scale phase difference between baryon and cdm.

Then the second order term of the interaction would look like

d1 d1 * + d1d2* + d2 d1* + d2 d2*

If d1 and d2 are out of phase seems like this will be smaller than when they are in phase. 

Another thing to watch out is aliasing. Smoothing and softening suppresses the generation of power in the point set density field at scales smaller than Nyquist of the PM mesh. This can cause the PM to see an aliased field that has less power and thus grow slower at large scale. (but can also go other way).

This can be checked. Can you measure the power spectrum of these fields all the way to the shotnoise regime with very fine mesh? We can look at this with and without DiffTransfer on both species. See if they are very different above the nyquist.

**Comment by sbird** [comment] 2018-07-25 02:13
Ok, I'll give that a go tomorrow.

**Comment by sbird** [comment] 2018-07-26 01:12
Here are the ratios with the CDM and baryon particles having roughly equivalent masses:

![part_002-full](https://user-images.githubusercontent.com/1325948/43235300-16ab139e-9035-11e8-862b-daf138a5f1f5.png)
![part_002](https://user-images.githubusercontent.com/1325948/43235301-16c37038-9035-11e8-8a5c-cc1c7c761f9d.png)

It does seem to agree better, although the CDM particle load is now rather small so there isn't much resolution. I'm not so sure why this is, or how to fix it beyond "oversample CDM" though.

**Comment by rainwoodman** [comment] 2018-07-26 01:15
You meant the baryon load is small?

**Comment by sbird** [comment] 2018-07-26 01:17
Yes, sorry.

**Comment by rainwoodman** [comment] 2018-07-26 01:32
Another thing to try is to increase baryon load, making them less massive
-- does it get worse?

**Comment by sbird** [comment] 2018-07-26 01:34
I'll try it

**Comment by sbird** [comment] 2018-07-26 06:31
It does get worse if I make baryons less massive by oversampling them relative to the CDM

**Comment by rainwoodman** [comment] 2018-07-26 20:32
1. In the limit where the second species are massless and slow, then they are captured and bound with the nearest DM particle. At linear scale they shall exactly follow the DM linear power, regardless their initial condition.

2. When they are massless yet with high velocity, they never fall into the nearest DM particle, then they shall follow the linear theory better.

3. When they are very massive, then they will interact with the DM particles as is, and still follow the linear theory.

Case 2 is neutrino, case 3 we also confirmed.

case 1 makes a prediction that the baryon power shall be identical to the DM power rather than the linear theory. But it doesn't sound consistent to your observation -- how different is the linear baryon power from the dm linear power?

**Comment by sbird** [comment] 2018-07-27 00:12
The above makes sense: note that the linear baryon power starts off about 50% of the linear CDM power and gradually catches up. The strange thing is that it does not catch up as fast as it should under linear theory.

**Comment by sbird** [comment] 2018-07-27 00:14
This seems like there is a second order term somewhere in the equations where for two species with masses M_i, M_j, M_i is getting accelerated  by (M_i + M_j)/2 instead of M_i...

**Comment by rainwoodman** [comment] 2018-07-27 00:30
No the first point doesn't work. It argues the baryon power shall catch up quickly with CDM, thus grow faster. 

As of (M_i + M_j) / 2 -- smells like reduced mass?

The neutrino says it has to do with binding energy. Notice that as you increase particle mass (subsample), the baryons are sparser and less fall into deep potential wells.

**Comment by rainwoodman** [comment] 2018-08-03 23:46
Update. We have a undergrad helping us to look at this more closely, starting by reproducing the issue with minimal test cases.

**Comment by Chris-Pedersen** [comment] 2018-08-09 16:53
Hi everyone, sorry for the long post and I’m probably redoing some things you’ve looked at but it might be useful to compare notes on this. I’ve been trying to reproduce figures from 2 papers. From [Angulo (2013)
](https://arxiv.org/abs/1301.7426):


![angulofig1](https://user-images.githubusercontent.com/16047009/43912264-a968faaa-9bf9-11e8-98b4-dc3c5d23391d.png)

and from [Valkenberg (2016)](https://arxiv.org/abs/1610.08501):

![pacofig3](https://user-images.githubusercontent.com/16047009/43912267-ad75f51c-9bf9-11e8-8bcf-23745d54400e.png)


It seems we have the inverse problem to these figures, which show baryon power too high with respect to linear theory, i.e. that baryons are catching up too fast to CDM power. I seem to be able to replicate Valkenberg Figure 3, but only with the Tree off, I think in the sims he ran he had the Tree on:


![cdmby_tree](https://user-images.githubusercontent.com/16047009/43912808-3b9c53da-9bfb-11e8-9741-e0462a69c491.png)


where in this sim the non-linear growth is reduced/delayed due to the fact that I started with 10% amplitude at z=99. The figure from Angulo's paper explores the effect of small scale force resolution, i.e. changing the softening length and the PM grid number. But I can’t recreate these effects – changing these parameters only affects power on small scales. In the plots below, we are comparing the P_by/P_CDM ratio in two sims. First we are comparing a Nmesh=2Ngrid sim with Nmesh=Ngrid (we have been using Nmesh=2Ngrid for all of our project sims so far):

![nmesheffect-1](https://user-images.githubusercontent.com/16047009/43913143-2c97c7ce-9bfc-11e8-8ab6-030c1fdd0e48.png)


In the plot below I change the baryon smoothing length to 0.01 for the 'LowSoft' sim, and 0.0666 for the 'HighSoft' (the change here is tiny so I might have done something wrong).


![softeffect-1](https://user-images.githubusercontent.com/16047009/43913159-345bed50-9bfc-11e8-9dae-9e105a0ca608.png)


So in both the baryon/CDM ratio is only altered at small scales. One question we don't understand is why does turning the Tree on have such a big effect at low k?

**Comment by sbird** [comment] 2018-09-01 21:00
A quick random thought about this (since @rainwoodman s undergrad is around to work on it):
Have we checked if the effect is different with glass files? I'm wondering if this is a problem with a staggered regular grid.

**Comment by andreufont** [comment] 2018-09-03 07:01
Hi @sbird - Chris is on vacation, but he should be able to run this test before the conference in Tokyo. Is it easy to use glass files? Could you point us to an example script for how to use them?

**Comment by andreufont** [comment] 2018-09-03 18:40
Hi @rainwoodman - If everything goes well, Chris and I will start running pretty large Lyman alpha simulations next Winter, and it would be quite important to have this working at least at the 1% level. I believe @sbird will start running simulations even earlier, so he probably has the tightest constraints. 

Once he is back from vacations, Chris will try to reproduce this error in Gadget-3.

**Comment by sbird** [comment] 2018-09-03 21:53
@andreufont : glass files I'm afraid are not at all easy to use - I don't think we support them in the IC generator anymore, as Yu said. I used one once but it's long gone now. Another similar possibility is using a Voronoi mesh (this thought was spawned by reading https://arxiv.org/abs/1807.03574 ).

**Comment by sbird** [comment] 2018-09-03 22:05
Probably the first thing to check is just how much, if at all, this actually affects the Lyman-alpha forest. This would mean generating flux power spectra with the current "different transfer functions = 1" vs  initialising them with the same, combined, transfer function. If these give the same answer for the flux power we can stop worrying about this, except as a problem for N-body codes.

The reason why it might not matter is that it goes away as z->0. It is 5% at z=9, but it decreases pretty rapidly and is much smaller by z=3. Plus it could easily be degenerate with the UVB amplitude. So someone should check.

**Comment by sbird** [comment] 2018-09-03 22:05
Note that the simulation from @Chris-Pedersen at the top of this issue is a now outdated version - the discrepancy with linear theory is much smaller now.

**Comment by rainwoodman** [comment] 2018-09-03 23:38
We shall at least be able to read and tile the CCVT text files. I'll add
this to the IC generator this week.

**Comment by andreufont** [comment] 2018-09-22 08:16
Hi @sbird @rainwoodman - @Chris-Pedersen has been doing more tests, and now it is quite clear that the issue is not only the ratio of baryon vs CMB power, but the total matter power is also off at the 2-3% level. 

@Chris-Pedersen - I would suggest to do more tests with CDM only, since at least this one should befine... Although now, looking at the list of issues I see that there are two issues that might be related to this: 
 - Verify large scale growth #182 
 - PETAPM=2,3 produces substantially different power to PETAPM=1 #70 

@sbird @rainwoodman - Could these be related?

**Comment by Chris-Pedersen** [comment] 2018-09-22 14:51
Hi @andreufont I'm still not entirely sure if its the case that the total matter is off. The test I ran yesterday looked fine for total matter, with just the baryon power too low so there may be something else going on in our case where we try to calculate the same power ratio in the sims as in CLASS. Let me verify DM-only first and try figure out if there's anything else that could be causing our current problem.

Also @sbird mentioned above we should check the effect on the Lya flux power to ensure that this issue matters; I ran the test for 3D flux a while ago and it is significant:

![lya_compare_norescale](https://user-images.githubusercontent.com/16047009/45918441-f731c600-bec1-11e8-8f84-a4872499cd2c.png)
![lya_compare_rescale](https://user-images.githubusercontent.com/16047009/45918442-fac54d00-bec1-11e8-95d7-0b2340709e91.png)

I think this difference is partially down to the fact that if we have DifferentTransfers off, the baryon power is 5% too high still at z=3 as it started way too high initially when compared with linear theory, when with DifferentTransfers on we have 5% too low. So there's a big difference in both the baryon power and the baryon/cdm ratio based on which IC method we use.

**Comment by sbird** [comment] 2018-09-23 03:14
Regarding the agreement with literature: it seems that we have good agreement between MP-Gadget with my code and Gadget3 with Paco's code (and we can use the conversion script to cross-check ICs, just to be safe). https://arxiv.org/abs/1301.7426 get a different answer, but they use MUSIC, which might be why. We could test this by generating MUSIC ICs for Gadget-3 and re-running a simulation.

**Comment by sbird** [comment] 2019-04-28 23:55
Fixed in master

**Closed by sbird** 2019-04-28 23:55 UTC

**Comment by andreufont** [comment] 2019-04-29 14:08
Hi @sbird - are we sure this issue is fixed? I know that you have done some progress with the GLASS files, but I'm not sure we are at the point where we can claim victory. Some of the plots in the draft look a bit worrying... In other words, if I was to run 100 expensive simulations tomorrow, I would still be worried about the linear growth in the simulations.

**Comment by sbird** [comment] 2019-04-29 17:02
The original offset issue is I think definitely fixed, although there may be subsidiary issues around the force resolution. If we find more bugs we can always open another issue - I like to keep issues small and easily digestable and for larger questions we can write papers.
