### ISSUE TITLE
Effective optical depth off by a factor of 3-5 in master

### ISSUE THREAD

**Issue by andreufont** [MP-Gadget/MP-Gadget#266] opened 2019-04-20 11:33 UTC
After updating MP-Gadget a few weeks ago I noticed that the mean flux was really off, I was getting mean flux=0.5 at z=5.

I did the following test: run two simulations with N=512 and L=30 Mpc/h, with exactly the same setting (Planck cosmology and Puchwein tree cool file), but using the latest version of MP-Gadget (from a couple of weeks ago) vs the "stable" version that Chris used in the neutrino project. l add here the comparison of the temperature and the mean flux. After adding the plots I just noticed that I got the labels wrong :-( 

@Chris-Pedersen suggested that this might be a consequence of some major recent changes in the cooling routines. 

![mf](https://user-images.githubusercontent.com/3873863/56456729-b410d600-6370-11e9-9490-ab590f3ffcb9.png)
![TDR](https://user-images.githubusercontent.com/3873863/56456730-b410d600-6370-11e9-9c7c-d21cc95e56ef.png)

**Comment by sbird** [comment] 2019-04-21 01:06
hmm, looks like the cooling code is working but there is a bug in the routine that outputs the neutral fractions. Thanks for the report, should be fixed soon. The slight changes in gamma for  z > z are likely a result of slightly more accurate integration routines for very cold gas.

**Comment by sbird** [comment] 2019-04-23 03:21
I did forget to fix the units: https://github.com/MP-Gadget/MP-Gadget/pull/267 should fix it, can you confirm?

**Comment by Chris-Pedersen** [comment] 2019-04-23 18:00
Confirmed that #267 fixes this.

**Comment by sbird** [comment] 2019-04-23 18:45
Merged, thanks!

**Closed by sbird** 2019-04-23 18:45 UTC
